#Set REMOTE_BROWSER_PLATFROM TO BS TO RUN ON BROWSERSTACK else
#SET REMOTE_BROWSER_PLATFORM TO SL TO RUN ON SAUCE LABS
REMOTE_BROWSER_PLATFORM = "BS"


USERNAME = "${env.USERNAME}"
ACCESS_KEY = "${env.ACCESS_KEYT}"






