"""
Conf file to hold Tesults target tokens:
Create projects and targets from the Tesults configuration menu: https://www.tesults.com
You can regenerate target tokens from there too. Tesults upload will fail unless the token is valid.

utils/Tesults.py will use the target_token_default unless otherwise specified
Find out more about targets here: https://www.tesults.com/docs?doc=target
"""

target_token_default = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjFmYzNjNTk4LTcwYzQtNDVmMi04YWZlLTMwM2EzYjJlNTZiNS0xNTI2Mzg1NzMzMDkxIiwiZXhwIjo0MTAyNDQ0ODAwMDAwLCJ2ZXIiOiIwIiwic2VzIjoiYzA0YmIzN2MtNDFhZS00ZjBlLTlmNDMtOGZkYTAxZmE0ZTkxIiwidHlwZSI6InQifQ.nFjREgm872JVXpx_UNfpKsp4xFssrV_e35bKvwDN_iI"
target_token_chrome = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjFmYzNjNTk4LTcwYzQtNDVmMi04YWZlLTMwM2EzYjJlNTZiNS0xNTI2Mzg1OTg0NzgyIiwiZXhwIjo0MTAyNDQ0ODAwMDAwLCJ2ZXIiOiIwIiwic2VzIjoiYzg5M2RmMjItMmM1Yi00NjFmLThlMDItNjU5MGI5NDE0NDE4IiwidHlwZSI6InQifQ.U17nzYit1wcA-78uX3TSWU3lai_Dr894SKkR8tZjNcI"
target_token_firefox = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjFmYzNjNTk4LTcwYzQtNDVmMi04YWZlLTMwM2EzYjJlNTZiNS0xNTI2Mzg2MDI0MDkyIiwiZXhwIjo0MTAyNDQ0ODAwMDAwLCJ2ZXIiOiIwIiwic2VzIjoiZjkwMjcxODYtYWQ1OS00ODVkLTgxZDktYzFhMzA3ZTA2OTMyIiwidHlwZSI6InQifQ.6kRGs1wY4_jGv0HbZklci3HRnb6UswyUbzajY_EbD_c"
target_token_safari = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjFmYzNjNTk4LTcwYzQtNDVmMi04YWZlLTMwM2EzYjJlNTZiNS0xNTI2Mzg2MDkyMzQ0IiwiZXhwIjo0MTAyNDQ0ODAwMDAwLCJ2ZXIiOiIwIiwic2VzIjoiODNmOTZjOGItNzIzYi00OTY5LTk0N2YtYmI3NWQ3NWI0YzdkIiwidHlwZSI6InQifQ.5PRBKMrRWvU4WhUQO8PkPF-N6elr0j1olf3dQ2PZid0"